# Please note that docker-compose does not prescribe a startup order

# microservice for tcpdump
opendlv-tcpdump:
    build: tcpdump
    net: "host"
    volumes:
    - /dumps:/dumps
    working_dir: "/dumps"
    command: /usr/sbin/tcpdump -G 900 -w '%Y-%m-%d_%H:%M:%S.pcap' -W 96


diagnostics-health:
    build: .
    net: "host"
    working_dir: "/opt/opendlv/bin"
    restart: always
    environment:
    - LD_LIBRARY_PATH=/opt/opendlv/lib
    command: "/opt/opendlv/bin/opendlv-system-core-diagnostics-health --cid=111 --freq=1"

